### PR TITLE
Branch to support postgres backend.

### PR DESCRIPTION
**Pull request by thomascirca**
Postgres is now supported as a backend.
Started moving to using md5s to uniquely identify files (still a TODO).
Some PEP8 stuff.

### CODE REVIEW

**Comment by worldveil** [comment]
This will be a really excellent addition, I think!

Ideally, I'd like the interface to the user to be the same and preferably break as little backwards compatibility as possible. 

Could you speak a little as to the differences in the postgresql implementation? Will the API be the same? For instance, "file" might be a better term than "song" but I don't want there to be wildy different terminology (and especially API) between the two. 

I've taken a look at it, but I'm more familiar with MySQL so was hoping you could explain a bit.

**Comment by nbtgit** [comment]
Hi, I am planning to implement mongodb support for this, i have DB with ~100,000 songs, each song 3-4mins. How do you think about Mongodb support, can mySQL handles such big data like that?

Thank you

**Comment by thomascirca** [comment]
@worldveil Yeah it's the same API - there's no difference, it should be a drop in replacement. Let me send another PR with isolated changes specifically for Postgres, that was poor form on my part for combining too many changes. I had used the word "file" instead of "song" as I'm fingerprinting stuff that isn't really "songs" and the word "song" was starting to drive me up the wall. I'll remedy that as well.

@nbtgit MySQL is fine for what you want, although Mongo would work well. Are you using a single Mongo instance, ie no sharding? The difference there is that since it's document oriented, you'd have to structure stuff a bit differently. I'd create two collections, one for "songs" and one for  "fingerprints". Same idea really, you'd just set the "_id" field of your "fingerprints" collection to whatever hash you generate for a segment of audio. Tracking what hash comes from what song could get interesting though.

**Comment by thomascirca** [comment]
@worldveil I should mention that all you need to do with the above change is to create another conf file and set "database_type" to "postgresql". That's the only change, as well as importing the new database class into the database.py file.

**Pull request closed without merging**
