### PR TITLE
Add Python 3 compatibility

### PR DESCRIPTION
**Pull request by nicktimko**
A bit slap-dash, but nothing major modified. Tweaks generally break down into 4 categories:
1. `print()`
2. Builtin/library generator wrangling (`xrange`, `izip`, forcing generator evaluation...)
3. Explicit relative imports (along with cleaning up imports I generally sorted them into stdlib vs. other)
4. Removing spaces at end of lines (because my editor does it automatically)

Another minor tweak was explicitly encoding a string (unicode in Python 3) into UTF-8 so it could be hashed. 

With the changes, running `example.py` works just fine, but let me know if you want the commits cleaned up a bit.

### CODE REVIEW

**Comment by nicktimko** [comment]
Forgot about the tests for some reason...  There was some trouble with `ast.literal_eval` (maybe the replaces to reformat the string weren't enough?), so I just did an end-around and used JSON. Python 3 absolutely requires consistent space/tab usage across the entire file, so I cleaned that in `run_tests.py` and for funsies the entire project after converting `example.py`

**Comment by worldveil** [comment]
My apologies for not looking at this sooner, I will do so this week!

**Comment by TOOTIS** [comment]
When will you add python3 compatibility?

**Comment by shoubamzlibap** [comment]
More interest in python3 here :)

**Comment by eracle** [comment]
Python3 is the future!

**Comment by Jack-Collins** [comment]
+1

**Comment by uhexos** [comment]
any luck with the python 3 yet ?

**Comment by loretoparisi** [comment]
Btw the python 2.7 deprecation is 2020 - https://pythonclock.org/
My question is: what is the reason to move to Python3 now?

**Comment by ryanmat** [comment]
Any word on this?

**Comment by deNsuh** [comment]
+1

**Comment by worldveil** [comment]
This has just been added!

**Pull request closed without merging**
