### PR TITLE
Update to Python 3

### PR DESCRIPTION
**Pull request by datawookie**
Hi,

This is a great package! I've been working with for a while now. However, since I do most of my work in Python 3 it's been a little frustrating that `dejavu` only works with Python 2.

I finally got around to making the necessary updates.

I've tested the code under Python 3 and everything seems to work well.

Please accept my changes and merge into the master repository.

Best regards,
Andrew.

### CODE REVIEW

**Comment by DataWookie** [comment]
Great.

**Comment by Hellowlol** [comment]
I’m looking forward for this.

**Comment by DataWookie** [comment]
@worldveil can we merge this?

**Comment by jrjames83** [comment]
Is this repo dead?

**Comment by DataWookie** [comment]
Yeah. No response from the repository owner. I'd be happy to pick this up.

**Comment by deNsuh** [comment]
Seems like we need a fork

**Comment by yeboahnanaosei** [comment]
Someone should please fork it. I don't do python. I would have done it a long time ago.

**Comment by DataWookie** [comment]
Cool. Okay, I already have a fork and I'm happy to bring across and apply the pull requests from the existing repository.

**Comment by noodlecak-e** [comment]
Link to the python3 repo please.

**Comment by DataWookie** [comment]
https://github.com/DataWookie/dejavu has been tested with Python 3. Would be great to have some independent validation though.

**Comment by DataWookie** [comment]
@worldveil Would you mind merging my pull request? Otherwise I'll go ahead and start maintaining a separate fork of this project with Python 3 support but, ideally, I'd prefer to keep everything in one place.

**Comment by sunravi** [comment]
@datawookie, great work. Thanks for updating to python3 and adding sqlite. I have been trying to use this in my windows 7 system. Does this work in windows?
Ravi

**Comment by datawookie** [comment]
@sunravi I don't know. I work on Linux.

Which repository are you working from?

**Comment by sunravi** [comment]
Sorry. If I understand correctly, I am working from the Dejavu fork you created

**Comment by datawookie** [comment]
Okay, then please create an issue on that repository.

**Pull request closed without merging**
