### PR TITLE
Windows support in the example.py

### PR DESCRIPTION
**Pull request by thesunlover**
just a small fixture to work on windows

### CODE REVIEW

**Comment by worldveil** [comment]
I don't understand how this fix helps windows users. This simply detects whether the file is being run directly, ie `python example.py`. 

Furthermore, I think multiprocessing already breaks on windows and I don't honestly care to support Windows.

**Comment by thesunlover** [comment]
Your answer is a bit strange. :)

what happens in windows is that it starts cycling on and on

key traceback looks like:

  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_li
ne
    is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

**Comment by worldveil** [comment]
so you are saying on windows, not having the `if __name__ == "__main__"` block is all it takes to make it work? I assume of course you have tested this.

**Comment by thesunlover** [comment]
yes, sure i tested it, its prety damn work i did to start it in Windows :) it took me a day untill i found the simple solution was this one line

**Pull request merged**
